### ISSUE TITLE
有没有方法判断按钮是用户点击发生改变还是用代码设置发生变化的,我的compoundButton.isPressed()一直为false

### ISSUE THREAD

**Issue by woshiqinwei** [kyleduo/SwitchButton#103]

**Comment by kyleduo** [comment]
你想实现什么效果？

**Comment by woshiqinwei** [comment]
如果是点击就触发状态改变的逻辑，如果是代码控制开关的话 就不触发改变的逻辑

**Comment by kyleduo** [comment]
`setCheckedNoEvent`方法可以不触发事件。

**Comment by HalyangDream** [comment]
> `setCheckedNoEvent`方法可以不触发事件。

想知道在回掉onCheckedChanged 如何判断是否是手指进行的按压操作

**Comment by benben1** [comment]
目前也遇到了这个问题，不知道有什么好的解决办法吗

**Comment by zuilintan** [comment]
![image](https://user-images.githubusercontent.com/34953840/103224943-c031a100-4963-11eb-9285-2f47c6eff35f.png)
原因是ACTION_UP时, setPressed(false)调用早于setChecked(nextStatus), 所以OnCheckedChangeListener回调时, buttonView.isPressed()始终为false, 即便是fromUser

**Comment by zuilintan** [comment]
可以将源码Clone到本地, 末置其调用时机重新打包引入解决

**Comment by zuilintan** [comment]
> `setCheckedNoEvent`方法可以不触发事件。

的确, 这是种方案, 不过一家人就要整整齐齐吗, 
特地试了下原生Switch, 
其OnCheckedChangeListener()中的buttonView.isPressed()是可以正常区分fromUser的, 
可以的话, 还是建议直接将这个修改同步一下哈
