### ISSUE TITLE
开始触摸SwitchButton,然后手指不在SwitchButton的宽高范围内滑动的时候，SwitchButton还是会不停的切换状态

### ISSUE THREAD

**Issue by humanheima** [kyleduo/SwitchButton#104]

**Comment by humanheima** [comment]
![switchbutton](https://user-images.githubusercontent.com/14139200/37134169-26e201da-22d2-11e8-9e2e-6757e7e6ab42.gif)

**Comment by kyleduo** [comment]
这是有意为之的

**Comment by humanheima** [comment]
好的，谢谢。不过，如果要手指不在View范围内就不在相应touch事件，能不能麻烦给提供个思路。

**Comment by kyleduo** [comment]
因为View的大小太小，所以如果离开View边界就终止的话容易误操作。
覆写`onTouchEvent`方法并适时返回false即可终止事件流。

**Comment by humanheima** [comment]
OK.Thanks a lot.
