### ISSUE TITLE
问一下为什么这个button上下自带padding？能去掉吗？

### ISSUE THREAD

**Issue by qinxianyuzou** [kyleduo/SwitchButton#112]
![tim 20180824150931](https://user-images.githubusercontent.com/10276840/44570374-3203e980-a7b0-11e8-9c6d-f46e333f9658.png)
如图，上下总有个边距，控件的高度、kswThumbHeight，kswThumbMarginTop这几个属性我都设置过了，没有效果，不知道这个边距怎么调？因为不能调的话很难布局。
然后我的是1.4.4版的，升级得后面再弄

**Comment by kyleduo** [comment]
发一下你xml的相关内容。

**Comment by qinxianyuzou** [comment]
> 发一下你xml的相关内容。

`<com.kyleduo.switchbutton.SwitchButton
            android:id="@+id/sb_switch_private_comment"
            style="@style/SwitchButtonMomentAlisBurning"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>`

其中SwitchButtonMomentAlisBurning是一下这样的

`    <style name="SwitchButtonMomentAlisBurning">
        <item name="kswThumbDrawable">@drawable/ksw_md_thumb</item>
        <item name="kswBackColor">@color/ksw_md_back_color</item>
        <item name="kswThumbMarginLeft">-16dp</item>
        <item name="kswThumbMarginTop">0dp</item>
        <item name="kswThumbMarginRight">-16dp</item>
        <item name="kswThumbMarginBottom">0dp</item>
        <item name="kswThumbHeight">10dp</item>
    </style>`

@kyleduo

**Comment by qinxianyuzou** [comment]
我看了一下2.0版本的demo源码也是有这个高度的，不知道这个怎么设置

**Comment by kyleduo** [comment]
MaterialDesign效果的话，是通过ThumbMargin来保证Thumb大小超过背景的范围。你看到的不是padding，而是Thumb，你可以打开debug开关看下Thumb的范围。
MaterialDesign效果，在按下的时候有半透明的阴影在。

**Comment by qinxianyuzou** [comment]
> MaterialDesign效果的话，是通过ThumbMargin来保证Thumb大小超过背景的范围。你看到的不是padding，而是Thumb，你可以打开debug开关看下Thumb的范围。
MaterialDesign效果，在按下的时候有半透明的阴影在。

不是MaterialDesign效果来的，不过确实是有阴影，应该就是Thumb，请问这个Thumb的大小怎么设置？我设置了kswThumbHeight这个属性并不生效

**Comment by kyleduo** [comment]
你现在用的Thumb就是MaterialDesign的Drawable。开下Debug，然后看下是不是Thumb给撑开的.

**Comment by qinxianyuzou** [comment]
> 你现在用的Thumb就是MaterialDesign的Drawable。开下Debug，然后看下是不是Thumb给撑开的.

懂了，原来是这个Drawable的问题，刚刚看到了这个Drawable，已经开过debug了，是Thumb撑大的，知道是Drawable的问题，那么我应该知道怎么改了，十分感谢

**Comment by kyleduo** [comment]
不客气
