### ISSUE TITLE
How to cover this will full blue

### ISSUE THREAD

**Issue by hafiz013** [kyleduo/SwitchButton#116]
![after click](https://user-images.githubusercontent.com/6707224/53547381-db65d680-3b69-11e9-8971-66ab92410c75.jpeg)
![before click](https://user-images.githubusercontent.com/6707224/53547389-e15bb780-3b69-11e9-928f-afd1043852bc.jpeg)

color code blue : #0000FF but it turn into light blue when do setTintColor. how to get full color blue?

**Comment by kyleduo** [comment]
`kswTintColor ` is used for convenient, to change the style by one property. You can set a color selector to `kswBackColor ` to make it work.
