### ISSUE TITLE
NullPointerException in SwitchButton.drawableStateChanged()

### ISSUE THREAD

**Issue by paraddiz** [kyleduo/SwitchButton#13]
Hi there!

I've got an issue with NullPointerException in SwitchButton.drawableStateChanged() - mConf is not initialized.
When I do android:enabled="false" in XML then drawableStateChanged() is calling before initView(). Because of there is super(context, attrs, defStyle) in constructor of course.

When I use setEnabled(false) for SwitchButton in code all work right.

**Comment by kyleduo** [comment]
fixed

**Comment by paraddiz** [comment]
Huh! Very fast, thank you! And for ADT? :)

**Comment by kyleduo** [comment]
Oh, I forgot that :P, and I'v finished it now.

**Comment by paraddiz** [comment]
Agreed. It works!
