### ISSUE TITLE
Failed build after removing jcenter() and changing to mavenCentral()

### ISSUE THREAD

**Issue by sca0610** [kyleduo/SwitchButton#132]
jcenter() have been deprecated recently, and after replacing it with mavenCentral(), project build failed with error "could not find com.kyleduo.switchbutton:library:2.0.3

**Comment by kyleduo** [comment]
Migration to mavenCentral is on the way.

**Comment by kyleduo** [comment]
Using version 2.1.0 please.

**Comment by sca0610** [comment]
Alright, thank you very much. 👍👍
