### ISSUE TITLE
Share source files for md drawables

### ISSUE THREAD

**Issue by iNPUTmice** [kyleduo/SwitchButton#15]
Hi,

I would like to be able to colourize the MD-style switch button as well (not just the normal one) However the md style button currently relies on some png files of which I can not change the color (or size for that matter)
Could you share the SVG files that where used to generate those png files?

**Comment by kyleduo** [comment]
Sorry, but I only created the .psd source file and you can get it in "res" folder.

**Comment by iNPUTmice** [comment]
Ok. Thank you.
