### ISSUE TITLE
Failed to resolve:com.kyleduo.switchbutton:library:1.2.8

### ISSUE THREAD

**Issue by mineshpatel1511** [kyleduo/SwitchButton#16]
Hi, 
I am trying to use this library but I get this error 
Failed to resolve:com.kyleduo.switchbutton:library:1.2.8. 
Can you please give proper maven url if any and the compile statement. I am using Android Studio and gradle.

**Comment by kyleduo** [comment]
I've try to add dependence in a new project and it worked okay. Please double check that you added this line in build.gradle file properly :  compile 'com.kyleduo.switchbutton:library:1.2.8'. BTW, my Gradle's version is 1.2.3.
