### ISSUE TITLE
Switch button with editText

### ISSUE THREAD

**Issue by sagits** [kyleduo/SwitchButton#17]
Hi, im trying to use switch button with an edittext inside an adapter. 
I have already implemented all the logic to save the pressed state and it works but when i set the switch on, it prevents me from focusing on the other views (Currently two editTexts). When i switch to false, i'm able to focus on the edittexts again.
   Can you help me please? Thanks in advance.

**Comment by sagits** [comment]
After some research i have found this to be an android view bug.

The setOnCheckedChangeListener is called multiple times when inside an adapter.
 I was using notifyDataSetChanged on this method, so it was been called several times per second and the ui was being blocked.

To solve this i used OnClickListener instead, but it fires before the switch state change, so i have to detect !switch.isChecked to check the after pressed state.

**Comment by kyleduo** [comment]
To make the EditText focused in ListView item, just add   android:descendantFocusability="afterDescendants" to ListView. But this is not the best solution because  it can make some other problems. Seriously, putting EditText into a ListView is not good idea.
