### ISSUE TITLE
Library still failed in drawableStateChanged() if getted by gradle

### ISSUE THREAD

**Issue by andrianovs** [kyleduo/SwitchButton#19]
Hello.

Issue https://github.com/kyleduo/SwitchButton/issues/13 was fixed in repository, but gradle download non fixed version.

Is available use
compile 'com.kyleduo.switchbutton:library:1.2.9'
or higher?

**Comment by kyleduo** [comment]
Could you please email your error log to me? I'm glad to help.

**Comment by andrianovs** [comment]
The problem is that library-1.2.8.jar (downloaded by "compile 'com.kyleduo.switchbutton:library:1.2.8'") doesn't contains the fix https://github.com/kyleduo/SwitchButton/commit/7644212872381587d658f089868edea849b48cff

I create simple AndroidStudio project. Put SwitchButton in layout:
```
	<com.kyleduo.switchbutton.SwitchButton
		android:enabled="false"
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		/>
```
And NPE happens in layout preview:
```
java.lang.NullPointerException
	at com.kyleduo.switchbutton.SwitchButton.drawableStateChanged(SwitchButton.java:522)
	at android.view.View.refreshDrawableState(View.java:16032)
	at android.view.View.setEnabled(View.java:6724)
	at android.widget.TextView.setEnabled(TextView.java:1446)
	at android.widget.TextView.<init>(TextView.java:983)
	at android.widget.Button.<init>(Button.java:111)
	at android.widget.CompoundButton.<init>(CompoundButton.java:82)
	at android.widget.CompoundButton.<init>(CompoundButton.java:78)
	at com.kyleduo.switchbutton.SwitchButton.<init>(SwitchButton.java:69)
	at com.kyleduo.switchbutton.SwitchButton.<init>(SwitchButton.java:100)
        ...
```
Same exception happen on device too.

**Comment by kyleduo** [comment]
Sorry for my mistake, change version to 1.2.9 will fix this. : P

**Comment by andrianovs** [comment]
Thank you.
Now fixed version available in repository for download by gradle.

**Comment by sunil0688** [comment]
Error:(37, 10) Failed to resolve: com.kyleduo.switchbutton:library:1.2.8
<a href="openFile:D:/solvur/Conversations-master/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by kyleduo** [comment]
Use latest version please. : )

**Comment by sunil0688** [comment]
i am only using mavencentral() , so your updated library present on the maven? and please tell me updated library version?

**Comment by kyleduo** [comment]
SwitchButton is on jcenter, add this line to you project:
```
allprojects {
    repositories {
        jcenter()
    }
}
```
 and latest version 'com.kyleduo.switchbutton:library:1.4.1' can be found in Readme easily.
