### ISSUE TITLE
Switch Button Size/width & height?

### ISSUE THREAD

**Issue by nasrul21** [kyleduo/SwitchButton#23]
how to change width/height of switch button.?
i tried to set layout_width and layout_height, but it doesn't work?

**Comment by MarKco** [comment]
I tried to resize the switch as well, but didn't manage to make it. That's weird!

**Comment by MarKco** [comment]
I don't want to overlook the job of kyleduo, but I managed to use the SwitchCompat view to do the trick: http://www.truiton.com/2015/03/android-switch-button-example/

**Comment by kyleduo** [comment]
You can change the size by set the thumbWidth and thumbHeight.

**Comment by kyleduo** [comment]
Update to 1.3.0 version please.

**Comment by kyleduo** [comment]
Version 1.3.1 anyway.
