### ISSUE TITLE
hi,i have some question for custom switch button.

### ISSUE THREAD

**Issue by wozuihighwa** [kyleduo/SwitchButton#27]
how to custom switch track height , seems track height cant change, same height as button icon .

my english not good,but hope you can help me. thx. ：）

**Comment by wozuihighwa** [comment]
我擦类，是国人啊~~~ 为啥 开关的 轨迹 高度 不能变得很细呢？ 求解答 谢谢啦。

**Comment by kyleduo** [comment]
Track's height is defined by the thumb height, and you can change it by setting the thumbMargin attributes. (用英语所有人都看得懂，所以还是英语吧^.^)

**Comment by wozuihighwa** [comment]
cant find the thumbMargin attributes, there is a thumbTextPadding,but didnt work. :(

**Comment by kyleduo** [comment]
kswThumbMargin, read the README please~
