### ISSUE TITLE
Demo App can not work in RedMI2(红米2)

### ISSUE THREAD

**Issue by cmos-cr** [kyleduo/SwitchButton#29]
Once SwitchButton is placed in ScrollView（activity_use.xml）, it can not slide after click and only splash like a button. I imported your project and built the demo app with Android Studio without changing any code.

当把 SwitchButton 放在ScrollView的LinearLayout中时（activity_use.xml），就只能像按钮一样响应点击并且只闪一下，不能自动滑动上面的滑块，也很难把滑块滑走。
在Nexus 6（android 5.1）上也一样，Easy to use中的SwitchButton都不能正常工作。

**Comment by kyleduo** [comment]
请多提供一些信息，Demo在我的设备上运行良好。Nexus5（Android 6.0）。

**Comment by cmos-cr** [comment]
在ScrollView里时，点击SwitchButton状态不能切换，左右轻微抖动。按住拖动滑块也很难拖走，放开后回到原处。点击时滑块像按钮一样改变背景，不切换状态。

**Comment by kyleduo** [comment]
确实很奇怪，暂时没有思路，有机会我复现下吧。

**Comment by cmos-cr** [comment]
我可以把工程编译的apk发给你。

**Comment by kyleduo** [comment]
发到kyleduo@gmail.com吧。

**Comment by cmos-cr** [comment]
发啦。

**Comment by kyleduo** [comment]
已经解决了，更新下代码吧。

**Comment by cmos-cr** [comment]
Thanks very much.
