### ISSUE TITLE
点击无响应

### ISSUE THREAD

**Issue by gh4work** [kyleduo/SwitchButton#31]
在ScrollView->LinearLayout->SwichButton的嵌套布局中，SwichButton的左右滑动是ok的，但是点击无响应，跪求解决

**Comment by kyleduo** [comment]
已经解决，请更新代码。

**Comment by gh4work** [comment]
遇到了另外一个问题：SwichButton的宽高都设置为wrap_content的时候，SwichButton上面和下面都有白色的边距，就像设置了padding_top和padding_bottom一样，而且上下的边距不相等，无法设置SwichButton在水平方向的LinearLayout中垂直居中显示，再次跪求解决
