### ISSUE TITLE
setOnCheckedChangeListener has no effect

### ISSUE THREAD

**Issue by ayltai** [kyleduo/SwitchButton#32]
Since SwitchButton extends CompondButton, I expect to use setOnCheckedChangeListener to track check state changes. But the implementation of onTouchEvent prevents this, such that we have to track the click event and check the isChecked value instead. Is there any chance you are going to update it?

Btw, thanks for the great component!

**Comment by kyleduo** [comment]
Anyway setOnCheckedChangeListener is available for SwitchButton and it is used in demo app as a common way. Plz paste your code and i'm glad to help.

**Comment by ayltai** [comment]
Thanks for point out this. I double check my code and it was my fault. Sorry!
Closing this issue.
