### ISSUE TITLE
Switch cropped in SwitchbuttonMD theme

### ISSUE THREAD

**Issue by m-radzikowski** [kyleduo/SwitchButton#33]
Using `SwitchbuttonMD` theme for SwitchButton in preview in Android Studio view is cropped too much, probably because of negative margins / measure ratio in styles.

Invalid view:
![switch_invalid](https://cloud.githubusercontent.com/assets/4042673/12036441/4deb7458-ae46-11e5-8554-357a15b279d9.png)

Desired view:
![switch_valid](https://cloud.githubusercontent.com/assets/4042673/12036447/53381132-ae46-11e5-82ad-472b45da3bdd.png)

However, after launching app SwitchButton displays correctly.

**But**, when using it in RecyclerView and scrolling down the list, new views are rendered badly (like on the 1st image). We have to scroll up and down again to have it displayed correctly.

**Comment by m-radzikowski** [comment]
PS. Simpliest hack is to set minWidth=60dp and minHeight=42dp in `SwitchbuttonMD` style - this is the size of switch when shown on device.

**Comment by kyleduo** [comment]
Thanks to point out, add these lines to style or just set into attributes can solve the problem.
```
<item name="kswThumbWidth">@dimen/ksw_md_thumb_ripple_size</item>
<item name="kswThumbHeight">@dimen/ksw_md_thumb_ripple_size</item>
```
I'll add these lines into default ``SwitchButtonMD`` style in next version.

**Comment by m-radzikowski** [comment]
Ok, thanks, works well.
