### ISSUE TITLE
SwichButton高度问题

### ISSUE THREAD

**Issue by gh4work** [kyleduo/SwitchButton#34]
SwichButton的宽高都设置为wrap_content的时候，SwichButton上面和下面都有白色的边距，就像设置了padding_top和padding_bottom一样，而且上下的边距不相等，无法设置SwichButton在水平方向的LinearLayout中垂直居中显示，希望楼主能解决

**Comment by kyleduo** [comment]
请贴一下xml的代码和截图。

**Comment by onecoders** [comment]
![image](https://cloud.githubusercontent.com/assets/3477738/12819597/a66fd7f0-cb96-11e5-8e10-a9013817e502.png)

**Comment by onecoders** [comment]
fix this with
![image](https://cloud.githubusercontent.com/assets/3477738/12819850/bea6e376-cb97-11e5-974d-bfd6b6787e90.png)
So Great!

**Comment by kyleduo** [comment]
Library fixed in 1.3.3 and these properties auto set in SwitchButtonMD style.
