### ISSUE TITLE
oncheckedchanged如何区分是用户点击还是代码设置的？

### ISSUE THREAD

**Issue by dotfeng** [kyleduo/SwitchButton#36]

**Comment by kyleduo** [comment]
onCheckedChanged不能不区分触发源，如果是希望使用代码控制开关而不想触发回调，可以在设置之前移除回调，设置之后再添加。另外，如果在onCheckedChanged中设置checked，是不会重复回调的。p.s.SwitchButton继承自CompoundButton行为和CheckedBox一致。
