### ISSUE TITLE
Fragment 中 setOnCheckChangeListener

### ISSUE THREAD

**Issue by WxSmile** [kyleduo/SwitchButton#37]
如果SwitchButton是  选中的，下次计入Fragment 会再次触发setOnCheckChangeListener

**Comment by kyleduo** [comment]
你是说调用了setOnCheckChangeListener还是说触发了Listener里的onCheckedChanged？如果是后者说明调用了setChecked方法，不想有回调的话可以在调用之前设置listener为null。

**Comment by WxSmile** [comment]
是onCheckedChanged，我解决了，好像是我的Fragment再次add to Stack的时候多次绘制了View，会触发onCheckedChanged。
因为我的需求是只是显示SwichButton的之前的状态，但是初始化的时候是没有调用setChecked方法的。

**Comment by kyleduo** [comment]
好的，如果不希望setChecked的时候出现动画，可以使用setCheckedImmediately方法。
