### ISSUE TITLE
怎么设置成IOS的样式

### ISSUE THREAD

**Issue by KingGGG** [kyleduo/SwitchButton#38]
我看到APK里面有IOS7的样式，但是属性却没找到~求大神help

**Comment by dotfeng** [comment]
app:kswAnimationDuration="300"
                    app:kswBackDrawable="@drawable/switch_back_selector"
                    app:kswBackMeasureRatio="2"
                    app:kswThumbDrawable="@drawable/switch_thumb_selector"/>

back

<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
	<item android:state_checked="true">
		<shape>
			<solid android:color="#43d95d"/>
			<corners android:radius="99dp"/>
		</shape>
	</item>
	<item>
		<shape>
			<solid android:color="#FFFFFF"/>
			<corners android:radius="99dp"/>
			<stroke
				android:width="1.5dp"
				android:color="#E6E6E6"/>
		</shape>
	</item>
</selector>

thumb

<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
	<item android:state_checked="true">
		<shape android:shape="oval">
			<solid android:color="#F8F8F8"/>
			<stroke
				android:width="1px"
				android:color="#D0D0D0"/>
		</shape>
	</item>
	<item>
		<shape android:shape="oval">
			<solid android:color="#F8F8F8"/>
			<stroke
				android:width="1px"
				android:color="#D0D0D0"/>
		</shape>
	</item>
</selector>

**Comment by kyleduo** [comment]
iOS的样式是通过图片的方式设置的，library中并不包含这个样式，你可以从Demo中找到相关的资源。
