### ISSUE TITLE
怎样导入才正确

### ISSUE THREAD

**Issue by 103king** [kyleduo/SwitchButton#39]
![20160229132534](https://cloud.githubusercontent.com/assets/17539770/13387818/884c62da-def5-11e5-8701-43dda99e649d.png)为什么我的导入之后出现这样的问题

**Comment by kyleduo** [comment]
如果用Eclipse的话，需要手动复制文件或者新建项目。SwitchButton不会影响项目原有的资源文件。图里的这个问题应该是因为support包配置不正确。
