### ISSUE TITLE
I use api22 have this problem ,can you help me? 

### ISSUE THREAD

**Issue by luhaoaimama1** [kyleduo/SwitchButton#43]
I nill use api23 ;only want to use api22 ~
`C:\Users\Administrator\AndroidStudioProjects\ZoneStudio233\Android_Zone_Test\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.1.0\res\values-v23\values-v23.xml
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.`

**Comment by kyleduo** [comment]
My suggestion is that import the project as module instead of Gradle, and change the support library version to  proper number.

**Comment by luhaoaimama1** [comment]
thanks ,I  put  your class  into my project .  now is ok~ very thanks
