### ISSUE TITLE
iOS Style Disabled State

### ISSUE THREAD

**Issue by randikachan** [kyleduo/SwitchButton#44]
Hi,

Thanks for the great help that's provided by your library.
But my requirement to use your library was just to imitate iOS Style Switch button. But unfortunately it seems like I can't get the minor feature of it when the iOS Style Switch button is in Disabled State.

Is there anyway to resolve this? Or have I been doing something wrong?

**Comment by kyleduo** [comment]
Hi, SwitchButton was not designed for a specific style like iOS. You can customize SwitchButton with images whatever you want. I've just add the missing disable style of iOS and you can checkout demo now.

**Comment by randikachan** [comment]
Okay, Great! Many thanks!
I will check that out!
