### ISSUE TITLE
how can i set checked without callback?

### ISSUE THREAD

**Issue by 531227501** [kyleduo/SwitchButton#45]
update 1.2.6
With calling the method setChecked(boolean, false);, you can change the status without invoking the listener.

there is the method setChecked(boolean, false) in the 1.2.6, but no longer in 1.4.0, so what should i do when i want to modify the check status whitout callback?

**Comment by 531227501** [comment]
@kyleduo is anyone here?

**Comment by kyleduo** [comment]
SwitchButton in 1.4.0 observe the behavier of CheckBox so you need remove callback before you call setChecked() and set it back after that.

**Comment by 531227501** [comment]
OK, i will try the way, thanks.

**Comment by kyleduo** [comment]
New feature supported in version 1.4.1.
