### ISSUE TITLE
Can the text be displayed on the Thumb

### ISSUE THREAD

**Issue by henjue** [kyleduo/SwitchButton#46]
Can the text be displayed on the Thumb
![1](https://cloud.githubusercontent.com/assets/1314740/14843233/1c9075c2-0c81-11e6-8827-c6fcdfefcf82.png)

**Comment by kyleduo** [comment]
This effect looks good and I think it calls "segment". SwitchButton does not focus on this so my suggestion is to search segment to get your answer or try other library. Thanks.

**Comment by henjue** [comment]
oh,thks
