### ISSUE TITLE
关于setOnCheckedChangeListener

### ISSUE THREAD

**Issue by morenever** [kyleduo/SwitchButton#48]
有没有那种只在状态切换时候的监听，
sb_md_open.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                if(isChecked) startActivity(new Intent(SetOptionActivity.this,MySetPatternActivity.class));
                else if(PatternLockUtils.hasPattern(getApplicationContext()))PatternLockUtils.clearPattern(getApplicationContext());
            }
        });
这样写，刚进入activity会直接走isChecked方法，但是我只是想在手动切换状态时执行。

**Comment by kyleduo** [comment]
onCheckedChanged方法在每次状态切换都会触发，如果希望默认SwitchButton是Check的，可以在xml中声明checked=true或者在设置check状态之后再设置监听。

**Comment by morenever** [comment]
ok thx
