### ISSUE TITLE
配合使用 Android 系统自带的 Preference,使用 自定义 SwitchPreference 时会有问题

### ISSUE THREAD

**Issue by maoruibin** [kyleduo/SwitchButton#53]
在我使用  SwitchPreference 结合 SwitchButton 做设置页面时，会出现奇怪的 UI 问题，每次更新 其他 Item 时。SwitchPreference 上的SwitchButton 会自动执行动画一次，
不知道，你有没有让 这个控件 跟 SwitchPreference 结合使用过，其实你可以在 demo  中 加入 设置页面中使用 SwitchButton 的示例，毕竟 这个控件跟 设置界面结合使用 比较多！

https://github.com/jenzz/Android-MaterialPreference

**Comment by benniaobuguai** [comment]
我也遇到这个问题了
