### ISSUE TITLE
Not able to set size for iOS switch

### ISSUE THREAD

**Issue by rahulchowdhury** [kyleduo/SwitchButton#57]
I copied and pasted code from your sample into my app, however the switch is appearing kind of huge
![screen shot 2016-07-05 at 4 23 23 pm](https://cloud.githubusercontent.com/assets/11270379/16582482/dcee1a96-42cc-11e6-8fd8-aea76dd1cd39.png)

Is there a way to control the size of the switch? I need it to be smaller.

**Comment by rahulchowdhury** [comment]
I also tried setting **thumbWidth** and **thumbHeight**, but no luck,

![screen shot 2016-07-05 at 4 31 22 pm](https://cloud.githubusercontent.com/assets/11270379/16582665/fa17251c-42cd-11e6-9660-acc63b825a97.png)

**Comment by kyleduo** [comment]
Which version are you using?

**Comment by kyleduo** [comment]
And did you put the iOS style drawable into correct folder "xhdpi"?

**Comment by rahulchowdhury** [comment]
Yeah, moving the images to "_xhdpi_" reduced the size, but I'm still not having total control over the thumb size using **thumbWidth** and **thumbHeight**.

**Comment by kyleduo** [comment]
Image drawable has it's minimal size, so if you use image drawable, SwitchButton will use the smaller one between ** thumbWidth** and **minimal size of drawable**.

**Comment by ysmintor** [comment]
@rahulchowdhury @kyleduo explained, I suggest you can make a smaller thumb drawable to use.

**Comment by rahulchowdhury** [comment]
@ysmintor @kyleduo Never mind I used the original image for the Switch
