### ISSUE TITLE
default color should fetch from the primary of theme.

### ISSUE THREAD

**Issue by machinezhou** [kyleduo/SwitchButton#60]
hi sir, 
Thanks for your work. And why default color of the button doesn't fetch from the primary color of theme just like Switch? Thanks again, it's a good lib.

**Comment by kyleduo** [comment]
I've supported this feature in version 1.4.2. But I use accent color but primary color, which is recommended is material design guideline. [Link](https://material.google.com/style/color.html#color-color-schemes)

**Comment by machinezhou** [comment]
OK， I'll check it out. Thanks.
