### ISSUE TITLE
Strange stuck, not the effect of the intermediate stop

### ISSUE THREAD

**Issue by yjiang2009** [kyleduo/SwitchButton#75]
Sometimes,the  ios style switchButton will slide a little inconsistency, it looks as if stuck. Of course, this is not the effect of the intermediate stop, I switched many times, always feel in addition to a standstill when switching, sometimes switching up, Strange stuck, particularly awkward.

**Comment by kyleduo** [comment]
I've find the problem and solved it. Witch order matters when mix two layer of different alpha. So make sure the z-order of on/off layers never change during slide from one endpoint to another.
Thanks for your feedback of this detail and sorry for the delay.
