### ISSUE TITLE
使用setCheckedImmediatelyNoEvent()遇到的bug

### ISSUE THREAD

**Issue by yjiang2009** [kyleduo/SwitchButton#78]
如果在初始化switchButton状态，利用sp值来改变，但不想调用oncheckedChanged时，在onCreate里调用setCheckedImmediatelyNoEvent()会出现调用了oncheckedChanged的情景。怀疑是和CompoundButton的onSaveInstanceState和onRestoreInstanceState有关系，放在onresume里就不会出现问题。应该是放在onCreate里导致onRestoreInstanceState的状态后执行，从而不是想要的结果。

**Comment by dhhAndroid** [comment]
你好,我也遇到这个bug了,在热编译和程序崩溃的时候会出现此bug.我已经解决此问题:方法如下,就是在onRestoreInstanceState方法里,将super的监听器移除,因为里面会调用setChecked(),有监听器的时候会调用监听器.具体代码如下:
    @Override
    public void onRestoreInstanceState(Parcelable state) {
        SavedState ss = (SavedState) state;
        setText(ss.onText, ss.offText);
        super.setOnCheckedChangeListener(null);//新加代码
        super.onRestoreInstanceState(ss.getSuperState());
        setOnCheckedChangeListener(mChildOnCheckedChangeListener);//新加代码
    }
