### ISSUE TITLE
SwitchButton在RelativeLayout中无法垂直居中

### ISSUE THREAD

**Issue by timshinlee** [kyleduo/SwitchButton#79]
问题如图
![image](https://cloud.githubusercontent.com/assets/23373307/20857343/cc4c2bd4-b963-11e6-89d9-1f2f1b2ef107.png)

已经参考了这篇问题https://github.com/kyleduo/SwitchButton/issues/34  ，设置style为SwitchButtonStyleMD，或者设置kswThumbWidth和kswThumHeight，但是还是无法解决，这是我的xml设置
![image](https://cloud.githubusercontent.com/assets/23373307/20857347/f23d5b1a-b963-11e6-9c94-86cbfd8c37a2.png)
麻烦帮我看看问题所在，谢谢！

**Comment by kyleduo** [comment]
因为Thumb阴影的存在，所以iOS的样式中，背景并不在View的中间，看起来也就不是居中的。可以使用paddingTop进行校正。
