### ISSUE TITLE
Can't set switch color

### ISSUE THREAD

**Issue by tianzhijiexian** [kyleduo/SwitchButton#8]
Thanks for your lib.I set thumbColor to MD switch button,it can't work.

    <com.kyleduo.switchbutton.SwitchButton
        android:id="@+id/sb_md"
        style="@style/MaterialDesignStyle" 
        app:onColor="#ff0000"/>

**Comment by kyleduo** [comment]
Thanks for using.

This mov shows how to customize SwitchButton with different colors. For
thumbColor, you need to use app:thumbColor and thumbPressedColor for
pressed status.

Have fun.

2015-01-18 10:00 GMT+08:00 Kale <notifications@github.com>:

**Comment by tianzhijiexian** [comment]
Thanks,I'll close this issue.
