### ISSUE TITLE
发现一个问题，求解决

### ISSUE THREAD

**Issue by chlss** [kyleduo/SwitchButton#81]
在调用setSwitchStates的时候，setOnCheckedChangeListener被调用了，怎么解决！

**Comment by kyleduo** [comment]
看ReadMe的Usage部分。

---

From version 1.4.1 on, SwitchButton support operation without onCheckedChanged callback. It makes changing state in code more convenient. Using these methods to achieve that feature.

setCheckedNoEvent(boolean)
setCheckedImmediatelyNoEvent(boolean)
toggleNoEvent()
toggleImmediatelyNoEvent()
