### ISSUE TITLE
How to import this project?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [kyleduo/SwitchButton#84]
I tried to clone it and open it, but got this:

![image](https://cloud.githubusercontent.com/assets/5357526/21808868/e0a7c810-d74d-11e6-9724-99cd56bfc50b.png)

**Comment by kyleduo** [comment]
If you just want to import SwitchButton as a library, you can use Gradle.

**Comment by AndroidDeveloperLB** [comment]
No. I wanted to import and see the sample.

**Comment by kyleduo** [comment]
Mis-click, sry about that.
Did you select the correct folder? You need select the sub-folder of project root.
<img width="259" alt="screen_capture" src="https://cloud.githubusercontent.com/assets/7019092/21852562/954d3664-d84e-11e6-87e9-565dc882f574.png">

**Comment by AndroidDeveloperLB** [comment]
I thought I'm supposed to open the top folder, as was done on all projects I've seen so far on Github.
I suggest you to do the same.
Anyway, I've now imported it. Works fine.
