### ISSUE TITLE
SwitchButton在恢复现场时,调用监听器的bug修复.方法如下,请及时更新.

### ISSUE THREAD

**Issue by dhhAndroid** [kyleduo/SwitchButton#85]
在热编译和程序崩溃的时候会出现此bug.我已经解决此问题:方法如下,就是在onRestoreInstanceState方法里,将super的监听器移除,因为里面会调用setChecked(),有监听器的时候会调用监听器.具体代码如下:
@Override
public void onRestoreInstanceState(Parcelable state) {
SavedState ss = (SavedState) state;
setText(ss.onText, ss.offText);
super.setOnCheckedChangeListener(null);//新加代码
super.onRestoreInstanceState(ss.getSuperState());
setOnCheckedChangeListener(mChildOnCheckedChangeListener);//新加代码
}

**Comment by kyleduo** [comment]
已更新
