### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by peakfa** [kyleduo/SwitchButton#87]
Failed to resolve: com.kyleduo.switchbutton:library:1.4.5
<a href="openFile:D:/androidDemo/ZmLauncher/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

  compileSdkVersion 25
    buildToolsVersion '25.0.0'

   minSdkVersion 19
        targetSdkVersion 25

**Comment by kyleduo** [comment]
Check your network connection pls.
