### ISSUE TITLE
How to set the text color

### ISSUE THREAD

**Issue by mengming** [kyleduo/SwitchButton#90]
I use the button in this way.
`<com.kyleduo.switchbutton.SwitchButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:kswTextOn="south"
        app:kswTextOff="north"
        app:kswThumbMargin="3dp"
        app:kswThumbColor="#ffffff"
        app:kswBackColor="#29b4dc"
        app:kswTintColor="#ffffff"/>`
Then this is the effect.
![image](https://user-images.githubusercontent.com/16859601/26960454-f3a83346-4d09-11e7-980b-a60420ad7a4e.png)

I want to change the text color, but it doesn't worked. How to solve this problem?
Waiting for you, thanks a lot!

**Comment by mengming** [comment]
I found the solution, thanks.

**Comment by squeeish** [comment]
Would you mind sharing the solution?
